<?php

namespace Bundles\AppBundle\Controller;

use Core\Controller\Controller;

Class AppController extends Controller {

    public function IndexAction($params){
        // Generated by the framework interface
    }
}